### PR TITLE
Add Next.js example for handling unsupported browsers

### PR DESCRIPTION
**Pull request by mislavmiocevic**
I made a section for Next.js that describes how to handle unsupported browsers more easily.

### CODE REVIEW

**Review by DarkoKukovec — COMMENTED** [review]
Regarding the regex, there was actually some work done to do it automatically based on the browserlist by using the browserslist-useragent-regexp package

**Comment by mislavmiocevic** [comment]
> Regarding the regex, there was actually some work done to do it automatically based on the browserlist by using the browserslist-useragent-regexp package

I didnt find anything related to Next.js and this package. Although you can go and copy paste regex and use it there.

**Review by isBatak — APPROVED** [review]

**Comment by andreicek** [comment]
@mislavmiocevic can we merge this?

**Comment by isBatak** [comment]
@mislavmiocevic can we merge this?
I can take this over if you don't have time.

**Comment by mislavmiocevic** [comment]
@isBatak if this is not a problem, can you please merge this? We have release in the following days so at the moment.
Thanks.

**Comment by mislavmiocevic** [comment]
> @mislavmiocevic can we merge this?

Sry, was on a vacation. @isBatak will merge this.

Thanks again.

@andreicek

**Pull request merged**
